"""Provider contract; domain methods are added by concrete providers."""
from typing import Protocol


class IntegrationProvider(Protocol):
    id: str

    def is_connected(self) -> bool: ...
    def connect(self): ...
    def disconnect(self) -> None: ...
    def test_connection(self): ...
    def get_account_info(self): ...
